"""add prod.trans tables

Revision ID: b05f652892a5
Revises: dbf9db04a8d2
Create Date: 2024-07-18 12:24:23.789220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05f652892a5'
down_revision = 'dbf9db04a8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companyName', sa.String(), nullable=True))
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('companyName')

    # ### end Alembic commands ###
